- project:
    check:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-queens
        - nuage-audit-rocky
        - nuage-audit-stein
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master
        - nuage-audit-queens-6-0
        - nuage-audit-rocky-6-0

    gate:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-queens
        - nuage-audit-rocky
        - nuage-audit-stein
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master

    periodic:
      jobs:
        - nuage-audit-queens

    periodic-sunday:
      jobs:
        - nuage-audit-rocky
        - nuage-audit-stein
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master
