- project:
    check:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-wallaby
        - nuage-audit-master

    gate:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-wallaby
        - nuage-audit-master

    periodic-sunday:
      jobs:
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-wallaby
        - nuage-audit-master
