- project:
    check:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-queens
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master

    gate:
      jobs:
        - openstack-tox-pep8
        - nuage-audit-queens
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master

    periodic:
      jobs:
        - nuage-audit-queens

    periodic-sunday:
      jobs:
        - nuage-audit-rocky
        - nuage-audit-train
        - nuage-audit-ussuri
        - nuage-audit-master
